In [2]:
import torch
from torch import nn

#建立词向量层
embedding = nn.Embedding(10, 3)
input = torch.LongTensor([[1,2,4,5],[4,3,2,9]])

In [3]:
embedding(input)

tensor([[[ 0.3128, -0.5044,  2.0763],
         [-0.6077, -0.6650,  1.6339],
         [ 0.2444, -0.5374, -1.7831],
         [ 0.9348,  0.4889, -1.2868]],

        [[ 0.2444, -0.5374, -1.7831],
         [ 0.4425, -0.1983,  0.3398],
         [-0.6077, -0.6650,  1.6339],
         [ 0.3346, -2.1781,  1.3258]]], grad_fn=<EmbeddingBackward0>)

In [4]:
embedding.weight

Parameter containing:
tensor([[ 0.7625, -0.9429,  0.6089],
        [ 0.3128, -0.5044,  2.0763],
        [-0.6077, -0.6650,  1.6339],
        [ 0.4425, -0.1983,  0.3398],
        [ 0.2444, -0.5374, -1.7831],
        [ 0.9348,  0.4889, -1.2868],
        [ 0.6794, -1.1540,  0.3649],
        [ 0.2196, -1.6245,  0.4682],
        [-0.1587, -0.6866, -1.5581],
        [ 0.3346, -2.1781,  1.3258]], requires_grad=True)

In [5]:
input

tensor([[1, 2, 4, 5],
        [4, 3, 2, 9]])

In [6]:
a = embedding(input)

In [7]:
a

tensor([[[ 0.3128, -0.5044,  2.0763],
         [-0.6077, -0.6650,  1.6339],
         [ 0.2444, -0.5374, -1.7831],
         [ 0.9348,  0.4889, -1.2868]],

        [[ 0.2444, -0.5374, -1.7831],
         [ 0.4425, -0.1983,  0.3398],
         [-0.6077, -0.6650,  1.6339],
         [ 0.3346, -2.1781,  1.3258]]], grad_fn=<EmbeddingBackward0>)

In [8]:
a.size()

torch.Size([2, 4, 3])